#!/bin/bash
cat <<EOF
SHELLY_URL=${SHELLY_URL:-''}
SHELLY_USER=${SHELLY_USER:-''}
SHELLY_PASSWORD=${SHELLY_PASSWORD=:-''}
SHELLY_ID=${SHELLY_ID:-''}
CLOUDANT_URL=${CLOUDANT_URL:-''}
CLOUDANT_DB_NAME=${CLOUDANT_DB_NAME:-''}
CLOUDANT_DB_NAME=${CLOUDANT_DB_NAME:-''}
IBMCLOUD_APIKEY=${IBMCLOUD_APIKEY:-''}
IBMCLOUD_URL=${IBMCLOUD_URL:-''}
APP_USER=${APP_USER:-''}
APP_APIKEY=${APP_APIKEY:-''}
APP_LOG=${APP_APIKEY:-''}
GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-''}
GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-''}
GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS:-''}
EOF